### ISSUE TITLE
CTRL+Backspace sends ^? instead of ^H

### ISSUE THREAD

**Issue by defue** [PowerShell/Win32-OpenSSH#1268]
Please answer the following

**"OpenSSH for Windows" version**
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
 
**Server OperatingSystem**
Windows 10 Pro Version 10.0.17763.55 Build 17763.55

**Client OperatingSystem**
Ubuntu 18.04

**What is failing**
When trying to use CTRL+backspace in the command prompt while being asked for input in Linux, it sends ^? instead of ^H and does not delete a word.

**Expected output**
When hitting CTRL+backspace it should delete a word.

**Actual output**
A character is deleted instead of a whole word

**Comment by maertendMSFT** [comment]
This is fixed in the latest release.

**Comment by defue** [comment]
In what release was it fixed? I've tried v8.1.0.0p1-Beta and it still doesn't work
