### ISSUE TITLE
Prompt is printed twice when exiting nano

### ISSUE THREAD

**Issue by anthonyvdotbe** [PowerShell/Win32-OpenSSH#1376]
**"OpenSSH for Windows" version**
7.7.2.2
 
**Server OperatingSystem**
Raspbian GNU/Linux 9 (stretch)

**Client OperatingSystem**
Windows 10 Pro (version 1809)

**What is failing**
To reproduce:
. run `ssh pi@foo`
. enter "nano"
. press Ctrl+X to exit nano

At this point, the prompt is printed twice.
I have also tried with `$env:TERM = 'xterm'`, but this didn't help.

**Expected output**
```
pi@foo:~ $ nano
pi@foo:~ $ 
```

**Actual output**
```
pi@foo:~ $ nano
pi@foo:~ $ pi@foo:~ $
```

Not sure if this helpful, but when connecting with -vvv, the actual output is as follows:
```
pi@sardien:~ $ nano
pi@sardien:~ $ debug2: client_check_window_change: changed
debug2: channel 0: request window-change confirm 0
debug3: send packet: type 98
pi@sardien:~ $ debug2: client_check_window_change: changed
debug2: channel 0: request window-change confirm 0
debug3: send packet: type 98

```

**Comment by cmd430** [comment]
I get this leaving `htop` and also after `clear`
![](https://i.imgur.com/NMiHlF1.png)

**Comment by tblut** [comment]
I get the same behavior when leaving `htop`, `nano` or using `clear` on build v7.9.0.0 when connecting to a Debian system.

**Comment by tblut** [comment]
I've tested this with version 8.0 and is still has the same issues. Additionally, this bug also appears when exiting or detaching a `screen` session.

**Comment by gadiel** [comment]
can confirm, it happens in both, powershell 5 and powershell 7 core lts.

**Comment by vlOd2** [comment]
Can also confirm, after using `clear`, `htop` and `nano` the terminal prompt is displayed twice and characters aren't displaying properly

**Comment by bagajjal** [comment]
@vlOd2 - This issue is fixed as part of [PR](https://github.com/PowerShell/openssh-portable/pull/426) shipped into V8.6. Can you please test your scenario with Win32-OpenSSH V8.9 / V8.6.

**Comment by vlOd2** [comment]
@bagajjal
The issue still persists. I do not know how to check the version, but I uninstalled the one from the settings and installed the latest v8.9 MSI file. I also changed my path just to be safe. The problem still persists.

**Comment by vlOd2** [comment]
@bagajjal
I can send you a recording...

**Comment by bagajjal** [comment]
@vlOd2 - You can check the SSH version number using `ssh -V`.

**Comment by vlOd2** [comment]
@bagajjal
OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3

**Comment by vlOd2** [comment]
@bagajjal
Also when using `tmux`, the problem is gone. Weird, maybe because `tmux` uses a different shell?

**Comment by vlOd2** [comment]
OpenSSH is unusable with this behaviour, the prompt becomes glitchy after using any terminal "fullscreen" app, or just by using clear

**Comment by AterialDawn** [comment]
This still happens with ssh version `OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2`

**Comment by o-sdn-o** [comment]
> This still happens with ssh version `OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2`

This might be fixed in https://github.com/PowerShell/openssh-portable/pull/806
