### ISSUE TITLE
Unable to logon with trusted AD User account

### ISSUE THREAD

**Issue by Kirderf73** [PowerShell/Win32-OpenSSH#399]
Hi!
I'm unable to SSH with a trusted AD user account (one way trust) on Win32-OpenSSH v0.0.2.0 to v0.0.3.0. It works on v0.0.1.0.

SSH with local AD users account works on all three versions.

**Win32-OpenSSH 0.0.1.0 (Works)**
**Win32-OpenSSH 0.0.3.0 (Failed password for invalid user )**

See attachments for log.
[openssh-log.zip](https://github.com/PowerShell/Win32-OpenSSH/files/578356/openssh-log.zip)

**Comment by manojampalam** [comment]
Authentication is done in agent. Verify and attach ssh-agent.log. See https://github.com/PowerShell/Win32-OpenSSH/wiki/Troubleshooting%20Steps

**Comment by Kirderf73** [comment]
Thanks for a great software!

I have uploaded the ssh-agent-log for both versions.

I had som problems to get the ssh logfile in debug3 though, but if "ssh -v" is enough, you have it in the zip.

[win32-openssh-ssh-agent-log.zip](https://github.com/PowerShell/Win32-OpenSSH/files/583360/win32-openssh-ssh-agent-log.zip)

**Comment by Kirderf73** [comment]
Hi!
Anything else you need?

Are the logs ok?

**Comment by manojampalam** [comment]
Thanks. Looked at the logs and found the point of failure. 
Invalid user eraxyz@ericsson.se from x.x.x.x

Need to investigate why sshd is unable to get user info for this particular user. sshd uses the following logic to get user info (in openssh-portable\contrib\win32\win32compat\pwd.c)
            if (NetUserGetInfo(udom_utf16, uname_utf16, 23, &user_info) != NERR_Success) {
                if (DsGetDcNameW(NULL, udom_utf16, NULL, NULL, DS_DIRECTORY_SERVICE_PREFERRED, &pdc) == ERROR_SUCCESS) {
                    if (NetUserGetInfo(pdc->DomainControllerName, uname_utf16, 23, &user_info) != NERR_Success ||

and this seems to be failing for a trusted AD User account.

**Comment by arif-pragmasys** [comment]
A potential fix of this issue is checked in: 
https://github.com/arif-pragmasys/openssh-portable/commit/53c6943f16c0e0c35b352332cd912c8b7ac237ea

**Comment by hugocelso** [comment]
Same here.
Extra context: AD user is in second domain <> ssh server domain, with thrust agreement.
Note 1: AD user and local ssh server user are ssh server machine admins.
Note 2: Not working at all with AD user or local ssh server user running ssh services (daemon + agent). (Local ssh server user with public key access stops working, password accepted but connection gets immediate "Connection reset by port 22".)
Note 3: Again with SSHD (daemon) and Local System (agent) restarted working for local ssh server user.
Note 4: AddressFamily inet in sshd_config to be able to log without GBs of "error: accept: Unknown error"
Versions: Windows Server 2012 R2 (ssh server) and OpenSSH-Win64 v0.0.4.0 (SSH-2.0-OpenSSH_7.3p1 Microsoft_Win32_port_with_VS)

Client lines:
(First local ssh server user ok, second ad user nok)

C:\Users\AD_USER>ssh local_ssh_server_user@ip.ip.ip.ip

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

local_ssh_server_user@ssh_server C:\Users\local_ssh_server_user>exitConnection to ip.ip.ip.ip closed.

C:\Users\AD_USER>ssh AD_USER@ip.ip.ip.ip
AD_USER@ip.ip.ip.ip's password:
Permission denied, please try again.
AD_USER@ip.ip.ip.ip's password:
Permission denied, please try again.
AD_USER@ip.ip.ip.ip's password:
Permission denied (publickey,password,keyboard-interactive).

C:\Users\AD_USER>ssh "AD_DOMAIN\AD_USER"@ip.ip.ip.ip
AD_DOMAIN\AD_USER@ip.ip.ip.ip's password:
Permission denied, please try again.
AD_DOMAIN\AD_USER@ip.ip.ip.ip's password:
Permission denied, please try again.
AD_DOMAIN\AD_USER@ip.ip.ip.ip's password:
Permission denied (publickey,password,keyboard-interactive).

C:\Users\AD_USER>ssh -l AD_USER@AD_DOMAIN ip.ip.ip.ip
AD_USER@AD_DOMAIN@ip.ip.ip.ip's password:
Permission denied, please try again.
AD_USER@AD_DOMAIN@ip.ip.ip.ip's password:
Permission denied, please try again.
AD_USER@AD_DOMAIN@ip.ip.ip.ip's password:
Permission denied (publickey,password,keyboard-interactive).

C:\Users\AD_USER>

sshd log:

6320 22:21:06 730 Server listening on 0.0.0.0 port 22.
5916 22:21:11 746 Connection from ip.cust.ip.cust port 60139 on 10.220.131.135 port 22
5916 22:21:11 793 Failed none for local_ssh_server_user from ip.cust.ip.cust port 60139 ssh2
5916 22:21:11 793 Postponed publickey for local_ssh_server_user from ip.cust.ip.cust port 60139 ssh2
5916 22:21:11 793 Accepted publickey for local_ssh_server_user from ip.cust.ip.cust port 60139 ssh2: RSA SHA256:key
5916 22:21:11 824 Starting session: shell on console for local_ssh_server_user from ip.cust.ip.cust port 60139 id 0
5916 22:21:14 793 Close session: user local_ssh_server_user from ip.cust.ip.cust port 60139 id 0
5916 22:21:14 793 Received disconnect from ip.cust.ip.cust port 60139:11: disconnected by user
5916 22:21:14 793 Disconnected from ip.cust.ip.cust port 60139
6184 22:21:21 746 Connection from ip.cust.ip.cust port 60141 on 10.220.131.135 port 22
6184 22:21:21 965 Invalid user AD_USER from ip.cust.ip.cust port 60141
6184 22:21:21 965 input_userauth_request: invalid user AD_USER
6184 22:21:21 965 Failed none for invalid user AD_USER from ip.cust.ip.cust port 60141 ssh2
6184 22:21:21 965 Failed publickey for invalid user AD_USER from ip.cust.ip.cust port 60141 ssh2
6184 22:21:21 965 Failed keyboard-interactive for invalid user AD_USER from ip.cust.ip.cust port 60141 ssh2
6184 22:21:25 918 Failed password for invalid user AD_USER from ip.cust.ip.cust port 60141 ssh2
6184 22:21:27 230 Failed password for invalid user AD_USER from ip.cust.ip.cust port 60141 ssh2
6184 22:21:27 590 Failed password for invalid user AD_USER from ip.cust.ip.cust port 60141 ssh2
6184 22:21:27 590 Connection closed by ip.cust.ip.cust port 60141
6584 22:21:38 465 Connection from ip.cust.ip.cust port 60145 on 10.220.131.135 port 22
6584 22:21:43 074 Invalid user AD_DOMAIN\AD_USER from ip.cust.ip.cust port 60145
6584 22:21:43 074 input_userauth_request: invalid user AD_DOMAIN\AD_USER
6584 22:21:43 074 Failed none for invalid user AD_DOMAIN\AD_USER from ip.cust.ip.cust port 60145 ssh2
6584 22:21:43 074 Failed publickey for invalid user AD_DOMAIN\AD_USER from ip.cust.ip.cust port 60145 ssh2
6584 22:21:43 074 Failed keyboard-interactive for invalid user AD_DOMAIN\AD_USER from ip.cust.ip.cust port 60145 ssh2
6584 22:21:46 730 Failed password for invalid user AD_DOMAIN\AD_USER from ip.cust.ip.cust port 60145 ssh2
6584 22:21:49 887 Failed password for invalid user AD_DOMAIN\AD_USER from ip.cust.ip.cust port 60145 ssh2
6584 22:21:52 918 Failed password for invalid user AD_DOMAIN\AD_USER from ip.cust.ip.cust port 60145 ssh2
6584 22:21:52 918 Connection closed by ip.cust.ip.cust port 60145
6744 22:31:46 951 Connection from ip.cust.ip.cust port 60245 on 10.220.131.135 port 22
6744 22:31:51 780 Invalid user AD_USER@AD_DOMAIN from ip.cust.ip.cust port 60245
6744 22:31:51 780 input_userauth_request: invalid user AD_USER@AD_DOMAIN
6744 22:31:51 780 Failed none for invalid user AD_USER@AD_DOMAIN from ip.cust.ip.cust port 60245 ssh2
6744 22:31:51 780 Failed publickey for invalid user AD_USER@AD_DOMAIN from ip.cust.ip.cust port 60245 ssh2
6744 22:31:51 780 Failed keyboard-interactive for invalid user AD_USER@AD_DOMAIN from ip.cust.ip.cust port 60245 ssh2
6744 22:31:57 046 Failed password for invalid user AD_USER@AD_DOMAIN from ip.cust.ip.cust port 60245 ssh2
6744 22:32:01 093 Failed password for invalid user AD_USER@AD_DOMAIN from ip.cust.ip.cust port 60245 ssh2
6744 22:32:04 609 Failed password for invalid user AD_USER@AD_DOMAIN from ip.cust.ip.cust port 60245 ssh2
6744 22:32:04 609 Connection closed by ip.cust.ip.cust port 60245

**Comment by hugocelso** [comment]
Solved. I had to use full domain!
I also upgraded to 0.0.5.0 (now reports SSH-2.0-OpenSSH_7.3) but I believe it was solved only because of full domain. Install dir now complains about admin rights, like when deleting logs (not a problem). Not sure if it is related to pid file creation error.

Command prompt is a bit buggy to custom usage but my purpose is scripting over, so I believe it will work as long as it is stable and it's possible to deal with ports back in fw. Many thx.

SSH Client:

C:\Users\AD_USER>ssh -l AD_USER@AD_DOMAIN.FULL_DOMAIN ip.ssh.srv.ip
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

AD_USER@AD_DOMAIN.FULL_DOMAIN@SSH_SERVER C:\Users\AD_USER>dir
 Volume in drive C has no label.

AD_USER@AD_DOMAIN.FULL_DOMAIN@SSH_SERVER C:\Users\AD_USER>exit
Connection to ip.ssh.srv.ip closed.

C:\Users\AD_USER>

sshd log:

4840 23:50:15 617 Server listening on 0.0.0.0 port 22.
4840 23:50:15 617 error: Couldn't create pid file "./sshd.pid": Permission denied
1876 23:50:25 945 error: Couldn't create pid file "./sshd.pid": Permission denied
1876 23:50:25 945 Connection from ip.ssh.cust.ip port 61650 on ip.ssh.srv.ip port 22
1876 23:50:26 086 Failed none for AD_USER@AD_DOMAIN.FULL_DOMAIN from ip.ssh.cust.ip port 61650 ssh2
1876 23:50:26 086 Postponed publickey for AD_USER@AD_DOMAIN.FULL_DOMAIN from ip.ssh.cust.ip port 61650 ssh2
1876 23:50:26 102 Accepted publickey for AD_USER@AD_DOMAIN.FULL_DOMAIN from ip.ssh.cust.ip port 61650 ssh2: RSA SHA256:key
1876 23:50:26 133 Starting session: shell on console for AD_USER@AD_DOMAIN.FULL_DOMAIN from ip.ssh.cust.ip port 61650 id 0
1876 23:50:36 961 Close session: user AD_USER@AD_DOMAIN.FULL_DOMAIN from ip.ssh.cust.ip port 61650 id 0
1876 23:50:36 961 Received disconnect from ip.ssh.cust.ip port 61650:11: disconnected by user
1876 23:50:36 961 Disconnected from ip.ssh.cust.ip port 61650

**Comment by Kirderf73** [comment]
Hi!
I've installed the latest v0.0.7.0 and it still doesn't work.

Thanks for taking your time to resolve this. :-)

[ssh-log.zip](https://github.com/PowerShell/Win32-OpenSSH/files/713876/ssh-log.zip)

//Fredrik

**Comment by hugocelso** [comment]
Bad news. I have it working, able to connect either way:
 * ssh user@full.domain@ip.ssh.srv.ip
 * ssh -l user@full.domain ip.ssh.srv.ip

I had lots of issues with architecture conectivity to all ADs. Have you checked windows ssh server for blocked conectivities?

**Comment by Kirderf73** [comment]
It works on v0.0.1.0 but not on any of the later releases.

The computer account is located in AD "ELD.FQDN" and the user accounts are located in "ERICSSON.FQDN". ELD has a one way trust to ERICSSON.
So the problem only occurs on ERICSSON user accounts, not on local ELD user accounts. 

Thanks!

**Comment by hugocelso** [comment]
That's my scenario, but here it works (like machine in ELD.FQDN):
ssh user@ERICSSON.FQDN@ip.sshsrv.eld.ip
ssh -l user@ERICSSON.FQDN ip.sshsrv.eld.ip
If you have and the time and patience :) and revert to v0.0.1.0, it still works?

**Comment by Kirderf73** [comment]
- Uninstalled version 0.0.7.0
- rebooted Windows 7 Ent
- Installed version 0.0.1.0

Tried this command and it worked perfectly. :-)
.\ssh.exe -l user@ericsson.FQDN localhost

**Comment by FrankWangAU** [comment]
Hi Guys,

I have the same problem with 0.0.7.0, any work around for this issue?

Thanks,
Frank

**Comment by topokina** [comment]
Hi all

Is there a solution to this issue. I have same problem.

**Comment by hugocelso** [comment]
Two cents comment: We (re) had when upgrading to v12, but it was solved with a note from a previous version that we had skipped (v11).
This info probably should be on install notes!
NOTE - Breaking Change
Due to a security issue that got fixed in this release, SSHD account now needs read access to authorized_keys. Otherwise pubkey authentication will fail. Do the following:
   $authorizedKeyPath = "c:\users\user\.ssh\authorized_keys"
   $acl = get-acl $authorizedKeyPath
   $ar = New-Object  System.Security.AccessControl.FileSystemAccessRule("NT Service\sshd", "Read", "Allow")
   $acl.SetAccessRule($ar)
   Set-Acl  $authorizedKeyPath $acl

**Comment by manojampalam** [comment]
Keeping this in radar for May-End release to see what can be done. Can someone provide the latest sshd and ssh-agent logs ?

**Comment by topokina** [comment]
Hi hugocelso

Thanks for the response.

I actually do not have "c:\users\user.ssh" but rather "C:\Users\SSHD". I believed this was created with the installation. 

Do I have to create "c:\users\user.ssh" or use "C:\Users\SSHD" instead. Or was there something not properly completed during my installation?

**Comment by hugocelso** [comment]
You need [.ssh] folder in the home directory of windows account that will be target for remote ssh (and authorized_keys file in it with keys), on windows server running openssh.

In my case the script was adapted like this:
$authorizedKeyPath = "G:\Users\user_ad_account\\.ssh\authorized_keys"
$acl = get-acl $authorizedKeyPath
$ar = New-Object  System.Security.AccessControl.FileSystemAccessRule("NT Service\sshd", "Read", "Allow")
$acl.SetAccessRule($ar)
Set-Acl  $authorizedKeyPath $acl

I can remote ssh with any of these command lines:
ssh user_ad_account@FQDN_ad@ip_windows_server_running_openssh
ssh -l user_ad_account@FQDN_ad ip_windows_server_running_openssh

**Comment by topokina** [comment]
I actually need users to access common home directory such as "E:\Download", from where they can download available files. They do not need access to any other folders such as "C:\Users"
In an old OpenSSH I used in the past, I had to create "passwd" file, in which the "home directory" for appropriate users are defined.

Do I have to address it same way in this application, or how do I go about defining such.

Thanks for your patience

**Comment by hugocelso** [comment]
This topic is all about trusted AD User account, in this scenario users will have to use one Active Directory account on target machine.
If all you want are users to access certain folders on a target machine then you probably don't need an AD account for that purpose, one or multiple limited local accounts will do better, or network shares.
Try the forum with ssh and key authentication in a simple scenario (without AD accounts).

**Comment by topokina** [comment]
Sorry for drifting off. The main challenges is getting trusted AD users to authenticate.

The issue is that the users in AD-Domain in which the Server is in are able to authenticate (SFTP) to the system, however any users coming from the trusted AD-Domain get "Access Denied", even though they could access any File-Shares on the Server.

**Comment by hugocelso** [comment]
I could be missing something here but as far as I know ssh will not use tokens from AD, so a passwordless system over ssh will use keys. It doesn't matter who you are in the client machine (as along as you have a valid key to authenticate), it only matters who you want to be on the target machine (with pub key in authorized_keys). If users are supposed to be themselves they will need some home account (usually under users folder), with their .ssh folder and authorized_keys with respective keys. Another (simpler) way could be one or few local acounts on target machine following needed permissions, servicing those users. SSHD subdir (in users folder) is for the account running the service.

**Comment by manojampalam** [comment]
Does this help: from https://github.com/PowerShell/Win32-OpenSSH/wiki/About-Win32-OpenSSH-and-Design-Details

•Authentication: ssh-agent will currently serve Basic and Key-Based authentication. It will be responsible for generating the client/user token once authentication succeeds. This includes: ◦key authentication - ensuring validity of public key mapping, validating a signed payload as part of client key based authentication and generating a Windows user token. Token generation is done using S4U for domain accounts and a custom SSP for local accounts.
◦Basic authentication - done using LogonUser.

**Comment by manojampalam** [comment]
I can help take this forward. Please reopen a new issue with the latest release (trouble shooting steps have changed).
